# language: node_js
# node_js:
# - '12'

# after_success: npm run coverage

# before_deploy:
# # clean up compiled files
# - git clean  -d  -fX -- "lib"
# - git clean  -d  -fX -- "templates"
# # compile files for package
# - npm run build-pack
# - node scripts/build-task.js
# - if [[ "${TRAVIS_TAG}" == *"beta"* || "${TRAVIS_TAG}" == *"alpha"* || "${TRAVIS_TAG}" == *"rc"* ]]; then export NPM_TAG="next"; else export NPM_TAG="latest"; fi
# # Copy populated .npmrc file to home dir to be used for publish
# - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

# deploy:
#   provider: script
#   script: lerna exec -- npm publish --tag "${NPM_TAG}"
#   skip_cleanup: true
#   on:
#     tags: true
#     repo: IgniteUI/igniteui-cli
#     branch: master

# env:
#   global:
#     # NPM_TOKEN=
#     secure: K/ypXHaMu3jEctoNT8tDR/iIDaMyNVNT2CqrYuByzrvceHBgWv7D3R1QnDF78Wx0iGNC/o6yx9uIkRLIpHWYK2qL/2U18lZZbAhrEXN3B5+hTr4eXkOnMrIz/vvkbZGdX/IhR8NII+todCGaUwKf84WVxknWA+BGol/XZ+BC6qhgv+G+EcTFQ1gcjz3poQ+BrEL/yK08SRATwbWelepQnb5fsJDp+/Q/TBuMV0SZI+WuK7/tzeg9kIIoPKRgmtqkkfheAnBJ2EVdH5wav6T79TfjANfzkQgF8WA4epnO3b4/6JXKY5GED6NhL1XwZXbOo/lvuHrH0BFm371xefjcP5xHBN+Yug0J18W8X2g8JSH8MOHysHsZo3GDEPSd0xwwRSfL9u4kQ/ie1VjGMITAu++MOdzO6YmqUUogacW7QFYsXp4zz7bTdsqU8MIt6aGzxh/Y97r4S9jbWYoVZ0AkOpbbs/2uEDgz3nKJSiiWbYfILUKRrZdujaEYLtfBJ9xnqzn9YN1oasnVTlXZFQ2Y9b2B1YLT3hqhAPnvf2Jp9Rfzo4s+3Ebb9HVXaw0iGk90i5VWW0H9WLpXTWn3GIUKG6qQZWgqFQfXzECn4xJgDrIMk6W2nnYBNHZ1REYnOHRn6Qo3AUhnWSx1tDRQPwl/yUenMuKPwnIKPMxAMJYlUwk=
