language: node_js
node_js:
- '10'

after_success: npm run coverage

before_deploy:
# clean up compiled files
- git clean  -d  -fX -- "lib"
- git clean  -d  -fX -- "templates"
# compile files for package
- npm run build-pack
# update package version
- npm version "$TRAVIS_TAG" --no-git-tag-version --save
- node scripts/build-task.js
- if [[ "${TRAVIS_TAG}" == *"beta"* ]]; then export NPM_TAG="next"; else export NPM_TAG="latest"; fi

deploy:
  tag: "${NPM_TAG}"
  provider: npm
  skip_cleanup: true
  email: igniteui@infragistics.com
  api_key:
    secure: hrxBzn0NvabRiucr8tUIey4KukijZ8yzN+CI7jNXklVShZq9qQttQ+8LMuW02wP+DcKkV5YojdpSuJ7MUVBP1pe39K2C13Hpw6Zd4qzQPyoLc0ZbQr20mwrgx8Z5J7Nt34dX9dg7wH+hEmn4qcXQAxrOeh6zgHs4HYmcAD6N8nc1rQ6fFO/p+dx4QemsYMQgkI3X319xQhIte2v9Mj6ssTIUWh2BRqXTEURmom7Kra4euCPb1vLDtDstGkKg2YlZ0VXWBXm3CaazmGXtIvyx18dHzf6QOS4lDbDFJ+bhc3Oqgjw1lRElICBEgtiMcRdoWlEvagynCXKLX8fkfi4hAhdH02pz6Dclp/u4hMshzUci3KWx+JQDidYgUcrDfEDmEIf8VO7dUG8rWN4FN3wojcX74rypCv1QLZRPPRcuCeLodx56V5A0kMeV3C4l9MLT5lCi3O5vr45+R35BaXb8J1srUJtwaMWTBCXoHsIYSo7V0utXhegaQNP0CmOMVKRyA00bjVcWzo0Q+Nk759EusGMjWBjv1LtQzAKrIvPVoYDPFPI0PnKHLe4FUirc5hNdiQmgOE0GST0+092t1jXqOzh5eERSc9RA5pjxvElWgO02xcivz9JLjsFYybGvPqan3u0x5U9Tzd0/9uvYPGB7eNP/YmdGvOqORg9zCG59huI=
  on:
    tags: true
    repo: IgniteUI/igniteui-cli
    branch: master
