name: Node.js CI

on:
  push:
    branches:  [ master, vNext, '[0-9]+.[0-9]+.x' ]
  pull_request:
    branches: [ master, vNext, '[0-9]+.[0-9]+.x' ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2 #make sure credentials are --global, so `New command` CLI tests pass
      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
           node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn --frozen-lockfile
      - name: Test
        run: |
          yarn config set scripts-prepend-node-path auto
          yarn test
      - name: Generate coverage
        if: matrix.node-version == '14.x'
        run: yarn coverage
      - name: Publish to coveralls.io
        if: matrix.node-version == '14.x'
        uses: coverallsapp/github-action@v1.1.2
        with:
            github-token: ${{ github.token }}