name: Yarn CI

on:
  push:
    branches: [ iganchev/ig-gh-actions-vNext ] #master, vNext, '[0-9]+.[0-9]+.x'
  pull_request:
    branches: [ iganchev/ig-gh-actions-vNext ] #master, vNext, '[0-9]+.[0-9]+.x'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
           node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn #run: yarn --frozen-lockfile 
      - name: Test
        run: |
          yarn config set scripts-prepend-node-path auto
          yarn test
      - name: Generate coverage
        if: matrix.node-version == '14.x'
        # run: nyc report --reporter=text-lcov --dir coverage lcov   
        run: yarn coverage
      - name: Publish to coveralls.io
        if: matrix.node-version == '14.x'
        uses: coverallsapp/github-action@v1.1.2
        with:
            github-token: ${{ github.token }}